### PR TITLE
Support specifying app_token when creating a message

### PR DESCRIPTION
**Pull request by cookieGeGe**
Support specifying app_token when creating a message

1. support specifying app_token when creating a message
2. conftest supports amd64

nox test result:

```
nox > Running session format
nox > Creating virtual environment (virtualenv) using python.exe in .nox\format
nox > python -m pip install black isort
nox > isort .
Skipped 4 files
nox > black .
All done! ✨ 🍰 ✨
9 files left unchanged.
nox > Session format was successful.
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python.exe in .nox\lint
nox > python -m pip install ruff
nox > ruff check .
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
  - 'ignore' -> 'lint.ignore'
  - 'select' -> 'lint.select'
  - 'pydocstyle' -> 'lint.pydocstyle'
  - 'per-file-ignores' -> 'lint.per-file-ignores'
All checks passed!
nox > Session lint was successful.
nox > Running session mypy
nox > Creating virtual environment (virtualenv) using python.exe in .nox\mypy
nox > python -m pip install '.[stream,test]' mypy
nox > mypy 
Success: no issues found in 8 source files
nox > Session mypy was successful.
nox > Running session test-3.9
nox > Missing interpreters will error by default on CI systems.
nox > Session test-3.9 skipped: Python interpreter 3.9 not found.
nox > Running session test-3.10
nox > Creating virtual environment (virtualenv) using python.EXE in .nox\test-3-10
nox > python -m pip install -e '.[stream,test]'
nox > pytest --cov --cov-report=xml --cov-report=term
========================================================================================================= test session starts =========================================================================================================
platform win32 -- Python 3.10.11, pytest-8.3.1, pluggy-1.5.0
rootdir: E:\code\gitee\python\python-gotify
configfile: pyproject.toml
testpaths: tests
plugins: anyio-4.4.0, asyncio-0.23.8, cov-5.0.0, typeguard-4.3.0
asyncio: mode=auto
collected 55 items                                                                                                                                                                                                                     

tests\test_async_gotify.py ............................                                                                                                                                                                          [ 50%]
tests\test_gotify.py ...........................                                                                                                                                                                                 [100%]

---------- coverage: platform win32, python 3.10.11-final-0 ----------
Name                       Stmts   Miss  Cover   Missing
--------------------------------------------------------
gotify\__init__.py             5      0   100%
gotify\async_gotify.py       131      6    95%   265, 269, 273, 277, 281, 285
gotify\errors.py              14      0   100%
gotify\gotify.py             121      6    95%   260, 264, 268, 272, 276, 280
gotify\response_types.py      58      0   100%
--------------------------------------------------------
TOTAL                        329     12    96%
Coverage XML written to file coverage.xml


========================================================================================================= 55 passed in 9.26s ========================================================================================================== 
nox > Session test-3.10 was successful.
nox > Running session test-3.11
nox > Creating virtual environment (virtualenv) using python.exe in .nox\test-3-11
nox > python -m pip install -e '.[stream,test]'
nox > pytest --cov --cov-report=xml --cov-report=term
========================================================================================================= test session starts =========================================================================================================
platform win32 -- Python 3.11.7, pytest-8.3.1, pluggy-1.5.0
rootdir: E:\code\gitee\python\python-gotify
configfile: pyproject.toml
testpaths: tests
plugins: anyio-4.4.0, asyncio-0.23.8, cov-5.0.0, typeguard-4.3.0
asyncio: mode=Mode.AUTO
collected 55 items                                                                                                                                                                                                                     

tests\test_async_gotify.py ............................                                                                                                                                                                          [ 50%]
tests\test_gotify.py ...........................                                                                                                                                                                                 [100%]

---------- coverage: platform win32, python 3.11.7-final-0 -----------
Name                       Stmts   Miss  Cover   Missing
--------------------------------------------------------
gotify\__init__.py             5      0   100%
gotify\async_gotify.py       131      6    95%   265, 269, 273, 277, 281, 285
gotify\errors.py              14      0   100%
gotify\gotify.py             121      6    95%   260, 264, 268, 272, 276, 280
gotify\response_types.py      58      0   100%
--------------------------------------------------------
TOTAL                        329     12    96%
Coverage XML written to file coverage.xml


========================================================================================================= 55 passed in 19.97s ========================================================================================================= 
nox > Session test-3.11 was successful.
nox > Running session test-3.12
nox > Missing interpreters will error by default on CI systems.
nox > Session test-3.12 skipped: Python interpreter 3.12 not found.
nox > Ran multiple sessions:
nox > * format: success
nox > * lint: success
nox > * mypy: success
nox > * test-3.9: skipped
nox > * test-3.10: success
nox > * test-3.11: success
nox > * test-3.12: skipped

```

### CODE REVIEW

**Comment by d-k-bo** [comment]
What is your usecase for this? If you want to create messages with different app tokens, the proper way is to create multiple `Gotify` objects.

For the sake of consistency, this change would require adding `app_token`/`client_token` to _every_ method, which would add a lot of unneccessary stuff to the code base.

I tend to be against this proposal.

**Comment by cookieGeGe** [comment]
Hello, thank you very much for your reply.


My usage scenario is to use a client to send messages to multiple apps based on the app_token sent. Initializing multiple instances or modifying the app_token before each message can indeed meet my needs.


I think that based on base_url and client_token, a client (for a gotify/server to initialize an object operation) can specify app_token separately when sending a message to a specified app. Only when the app_token is not specified when sending a message, the app_token specified at initialization is used as the default value. There is no need to add app_token/client_token to each method, because client_token is used to identify the current client, app_token is used to send messages, and only create_message needs to use app_token, so I think only this method needs to be changed, and the others remain unchanged, which makes it more convenient for us to use an instance object (client) to send messages to multiple apps.

&nbsp;


张应云
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2024年7月23日(星期二) 凌晨1:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [d-k-bo/python-gotify] Support specifying app_token when creating a message (PR #5)














 
What is your usecase for this? If you want to create messages with different app tokens, the proper way is to create multiple Gotify objects.
 
For the sake of consistency, this change would require adding app_token/client_token to every method, which would add a lot of unneccessary stuff to the code base.
 
I tend to be against this proposal.

**Comment by cookieGeGe** [comment]
Hello, thank you very much for your reply.

My usage scenario is to use a client to send messages to multiple apps based on the app_token sent. Initializing multiple instances or modifying the app_token before each message can indeed meet my needs.

I think that based on base_url and client_token, a client (for a gotify/server to initialize an object operation) can specify app_token separately when sending a message to a specified app. Only when the app_token is not specified when sending a message, the app_token specified at initialization is used as the default value. There is no need to add app_token/client_token to each method, because client_token is used to identify the current client, app_token is used to send messages, and only create_message needs to use app_token, so I think only this method needs to be changed, and the others remain unchanged, which makes it more convenient for us to use an instance object (client) to send messages to multiple apps.

**Comment by d-k-bo** [comment]
Sorry for my late response. I was on vacation and now I am pretty busy preparing for an upcoming exam. It might take a while until I can look into this.

**Comment by d-k-bo** [comment]
Sorry that it took a while longer to get back to this.

I am not convinced that this is generally practical addition to this library. It complicates things and doesn't fit the idea that each `Gotify` object is specific to one App <-> Server connection.

For your purpose I suggest that you use either multiple `Gotify` objects or create a custom subclass that implements this feature.

Nevertheless, thank you for your proposal!

**Pull request closed without merging**
